spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://k8a702.p.ssafy.io:3306/feelingfilling?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: mammoth77
    url: jdbc:mysql://localhost:3306/feelingfilling
    password: 1234
    username: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/feelingfilling
#      uri: mongodb:////k8a702.p.ssafy.io:27017
#      authentication-database: admin
#      database: feelingfilling



jwt:
  secret: makemoneyfromyouremotionandfeelbetter
  jackson:
    serialization:
      fail-on-empty-beans: false

