spring:
  security:
    oauth2:
      client:
        registration:
#          google:
#            client-secret:
#            client-id:
#            scope:
#              - email
#              - profile
#          naver:
#            client-secret:
#            client-id:
#            scope:
#              - name
#              - email
#              - profile_image
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            redirect-uri:
          kakao:
            client-id: ${OAUTH2_KAKAO_ID}
            client-secret: ${OAUTH2_KAKAO_SECRET}
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            redirect-uri: https://k8a702.p.ssafy.io:8080/login/oauth2/code/kakao
        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
