# Generated by Django 3.2.13 on 2023-04-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('chatting_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('chat_date', models.DateTimeField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'chatting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('react_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('emotion', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'react',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('request_time', models.DateTimeField()),
                ('translation', models.CharField(max_length=200)),
                ('react', models.CharField(blank=True, max_length=200, null=True)),
                ('emotion', models.CharField(blank=True, max_length=20, null=True)),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('join_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('user_badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('badge_id', models.PositiveIntegerField()),
                ('achived_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_badge',
                'managed': False,
            },
        ),
    ]
