version: '3'
services:

  django:
    container_name: django
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SERVER_MODE: prod
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    # command: python manage.py runserver 0.0.0.0:8000 --noreload
    ports:
      - "8000:8000"
